import localFont from "next/font/local";
import "./globals.css";
import AuthProvider from "@/components/custom/AuthProvider";
import TopNav from "@/components/custom/nav/top-nav";
import { ThemeProvider } from "next-themes";
import { Toaster } from "sonner";
import { UsageProvider } from "@/context/usage";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "AI Content Gen",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <UsageProvider>
              <TopNav />
              <main>
                {children}
              </main>
              <Toaster richColors />
            </UsageProvider>
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
